version: "3.1"
services:
    php:
      image: git.pine.com.ua:4567/dinarys/reales:${VERSION}
      container_name: ${APP_NAME}
      environment:
        - VERSION
        - HTTP_PORT
      working_dir: /var/www
      volumes:
        - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime
        - vendor:/var/www/vendor
        - node_modules:/var/www/node_modules
        - /data/common/reales/storage:/var/www/storage
        #- /var/log/${APP_NAME}/laravel:/var/www/storage/logs
        #- .docker/env.prod:/var/www/.env
        - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - .docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - .docker/nginx/host.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${HTTP_PORT}:8001"

volumes:
  vendor:
  node_modules:
