version: "3.1"
services:
    php:
      image: git.pine.com.ua:4567/dinarys/reales:${VERSION}
      container_name: ${APP_NAME}
      environment:
        - VERSION
        - HTTP_PORT
        - WS_PORT
      working_dir: /var/www
      volumes:
        - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime
        - vendor:/var/www/vendor
        - node_modules:/var/www/node_modules
        - storage:/var/www/storage
        - /var/log/${APP_NAME}/laravel:/var/www/storage/logs
        - .docker/env.stage:/var/www/.env
        - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - .docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - .docker/nginx/host.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${HTTP_PORT}:8001"
      depends_on:
        - mysql

    mysql:
      image: mysql:5.7
      container_name: ${APP_NAME}_mysql
      environment:
        - VERSION
        - HTTP_PORT
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=reales
        - MYSQL_USER=reales
        - MYSQL_PASSWORD=123123
        - MYSQL_ROOT_PASSWORD=987654321
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime
        - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  vendor:
  node_modules:
  storage:
